spring:
  application:
    name: bff
  main:
    web-application-type: reactive

server:
  port: 8084

gateway:
  url: ${GATEWAY_URL:http://api-gateway:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    cl.smartlogix.bff: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%p","correlationId":"%X{correlationId}","message":"%m","logger":"%c"}%n'

resilience4j:
  circuitbreaker:
    instances:
      gateway:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
